# Generated by Django 2.1.1 on 2018-10-08 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0013_auto_20181005_1555'),
        ('formacao', '0007_auto_20181004_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': 'Ações',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pdi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Título do PDI')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'PDI',
                'verbose_name_plural': 'PDI',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='PdiCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.CharField(max_length=250, verbose_name='Prazo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.Curso', verbose_name='Curso')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.Instituicao', verbose_name='Instituição')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'PDI - Curso',
                'verbose_name_plural': 'PDI - Curso',
                'ordering': ['curso'],
            },
        ),
        migrations.CreateModel(
            name='PdiEspecializacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.CharField(max_length=250, verbose_name='Prazo')),
                ('especializacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.Especializacao', verbose_name='Especialização')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.Instituicao', verbose_name='Instituição')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'PDI - Especialização',
                'verbose_name_plural': 'PDI - Especialização',
                'ordering': ['especializacao'],
            },
        ),
        migrations.CreateModel(
            name='PdiFormacaoAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.CharField(max_length=250, verbose_name='Prazo')),
                ('formacao_academica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.FormacaoAcademica', verbose_name='Formação')),
                ('instituicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.Instituicao', verbose_name='Instituição')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'PDI - Formação Acadêmica',
                'verbose_name_plural': 'PDI - Formação Acadêmica',
                'ordering': ['formacao_academica'],
            },
        ),
        migrations.CreateModel(
            name='PdiIdioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prazo', models.CharField(max_length=250, verbose_name='Prazo')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacao.Idioma', verbose_name='Idioma')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'PDI - Idioma',
                'verbose_name_plural': 'PDI - Idioma',
                'ordering': ['idioma'],
            },
        ),
        migrations.CreateModel(
            name='PdiProfissional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel', models.CharField(max_length=250, verbose_name='Responsável')),
                ('prazo', models.CharField(max_length=250, verbose_name='Prazo')),
                ('metrica', models.CharField(max_length=250, verbose_name='Métrica')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Acao', verbose_name='Ação')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'PDI - Profissional',
                'verbose_name_plural': 'PDI - Profissional',
                'ordering': ['acao'],
            },
        ),
    ]
