# Generated by Django 2.1.1 on 2018-10-09 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0007_auto_20181004_1139'),
        ('pdi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdiespecializacao',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formacao.Curso', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pdiformacaoacademica',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formacao.Curso', verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
