# Generated by Django 2.2.4 on 2020-03-22 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdi', '0002_auto_20181009_0838'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pdi',
            options={'verbose_name': 'PDI', 'verbose_name_plural': 'PDI'},
        ),
        migrations.RemoveField(
            model_name='pdi',
            name='nome',
        ),
    ]
