# Generated by Django 2.2.4 on 2020-03-22 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0010_auto_20200207_0919'),
        ('pdi', '0003_auto_20200322_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdiCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Acao', verbose_name='Ação')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao_avaliacao_desempenho.Competencia', verbose_name='Competência')),
                ('pdi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdi.Pdi', verbose_name='PDI')),
            ],
            options={
                'verbose_name': 'PDI - Competência',
                'verbose_name_plural': 'PDI - Competências',
                'ordering': ['acao'],
            },
        ),
    ]
