# Generated by Django 2.1 on 2018-09-19 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0007_auto_20180918_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnaliseTalento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.IntegerField()),
                ('avaliacao', models.TextField(blank=True, verbose_name='Avaliação')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('comunicacao', models.BooleanField(help_text='Desenvoltura, Coerencia entre discurso e acao, objetividade, capacidade de transmitir ideias e escutar. Capacidade de se comunicar com diferentes tipos de pessoas.', null=True, verbose_name='Comunicação')),
                ('negociacao', models.BooleanField(help_text='Capacidade de Argumentacao, persuasao, Adm de conflitos, respeito as pessoas e foco no resultado.', null=True, verbose_name='Negociação')),
                ('comportamento', models.BooleanField(blank=True, default=False, help_text='Autoconfianca e auto conhecimento.', null=True, verbose_name='Comportamento')),
                ('competitividade', models.BooleanField(blank=True, default=False, help_text='Metas claras e esfocos para se chegar aos objetivos comuns.', null=True, verbose_name='Competitividade')),
                ('criatividade', models.BooleanField(blank=True, default=False, help_text='Pensar intuitivamente, pensar e tentar novas formas.', null=True, verbose_name='Criatividade')),
                ('inovacao', models.BooleanField(blank=True, default=False, help_text='Sair da zona de conforto, possui visao ampla novos focos, novas formas de fazer as coisas.', null=True, verbose_name='Inovação')),
                ('protagonismo', models.BooleanField(blank=True, default=False, help_text='Iniciativa, entusiasmo, brilho nos olhos.', null=True, verbose_name='Protagonismo')),
                ('equilibrio_emocional', models.BooleanField(blank=True, default=False, help_text='Capacidade de Trabalhar sob Pressao, Resistencia a Frustracao e Maturidade. Autocontrole emocional.', null=True, verbose_name='Equilíbrio Emocional')),
                ('solucao_problemas', models.BooleanField(blank=True, default=False, help_text='Analise critica, Coerencia, Flexibilidade, Improvisacao, adaptacao a mudancas, diversidade.', null=True, verbose_name='Solução de Problemas')),
                ('etica', models.BooleanField(blank=True, default=False, help_text='Transparencia e confiabilidade. Integridade.', null=True, verbose_name='Ética')),
                ('gestao_negocio', models.BooleanField(blank=True, default=False, help_text='Atualizado, tem opiniao sobre onde a empresa esta, para onde vai e realiza previsoes.', null=True, verbose_name='Gestão de Negócio')),
                ('gestao_pessoas', models.BooleanField(blank=True, default=False, help_text='Delega tarefas, identifica talentos e desenvolve, envolve, trabalha para pessoas e nao para tarefa,tratar de forma personalisada, ampliar a rede de relacionamento. Pedir opiniao.', null=True, verbose_name='Gestão de Pessoas')),
                ('tomada_decisao', models.BooleanField(blank=True, default=False, help_text='Analise de informacoes, Compartilha e pede opinioes, riscos.', null=True, verbose_name='Tomada de Decisão')),
                ('accontability', models.BooleanField(blank=True, default=False, help_text='Comprometimento, resolutividade, entrega, visao de dono.', null=True, verbose_name='Accontability')),
                ('excelencia_operacional', models.BooleanField(blank=True, default=False, help_text='Ir alem das metas e objetivos (resolutividade), realizar o trablaho com excelencia e produtividade.', null=True, verbose_name='Excelência Operacional')),
                ('atendimento_cliente', models.BooleanField(blank=True, default=False, help_text='Descobrir os desejos ocultos dos clientes, investir tempo sobre as necessidades das outras pessoas.', null=True, verbose_name='Atendimento ao Cliente')),
                ('relacionamento_interpessoal', models.BooleanField(blank=True, default=False, help_text='Domina a cultura da organizacao e otimiza os relacionamentos e mantem bom relacionamento com os fornecedores e clientes.', null=True, verbose_name='Relacionamento Interpessoal')),
                ('trabalho_equipe', models.BooleanField(blank=True, default=False, help_text='Cooperar, ter a empatia, ou seja a sencibilidade para lidar com os outros, colaborar, escutar e respeitar opinioes, trabalhar em conjunto, aceitar criticas.', null=True, verbose_name='Trabalho em Equipe')),
                ('aprendizado_desenvolvimento', models.BooleanField(blank=True, default=False, help_text='Capacidade de iniciar novas atividades, novos enfoques e formas de fazer as coisas.', null=True, verbose_name='Aprendizado e Desenvolvimento')),
                ('gestao_mudanca', models.BooleanField(blank=True, default=False, help_text='Necessidades constantes de adaptacao, criacao de projetos ou iniciativas para melhorar o desempenho, resultados ou aproveitar oportunidades, gerando mudanças em processos, funções de trabalho, estruturas organizacionais e usos de novas tecnologias.', null=True, verbose_name='Gestão da Mudança')),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.AddField(
            model_name='analisetalento',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='analisetalento',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa'),
        ),
    ]
