# Generated by Django 2.1 on 2018-09-19 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisetalento',
            options={'verbose_name': 'Análise de Talento', 'verbose_name_plural': 'Análises de Talentos'},
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='descricao',
        ),
    ]
