# Generated by Django 2.1 on 2018-09-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_auto_20180919_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
