# Generated by Django 2.1 on 2018-09-19 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0005_auto_20180919_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisetalento',
            name='nota_curso',
            field=models.CharField(max_length=30, verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='analisetalento',
            name='nota_especializacao',
            field=models.CharField(max_length=30, verbose_name='Especialização'),
        ),
        migrations.AlterField(
            model_name='analisetalento',
            name='nota_formacao_academica',
            field=models.CharField(max_length=30, verbose_name='Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='analisetalento',
            name='nota_idioma',
            field=models.CharField(max_length=30, verbose_name='Idiomas'),
        ),
        migrations.AlterField(
            model_name='analisetalento',
            name='nota_performance',
            field=models.CharField(max_length=30, verbose_name='Performance'),
        ),
        migrations.AlterField(
            model_name='analisetalento',
            name='nota_total',
            field=models.CharField(max_length=30, verbose_name='Nota Total'),
        ),
    ]
