# Generated by Django 2.1 on 2018-09-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0008_auto_20180919_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_cursos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nota Máxima para Cursos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_especializacao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nota Máxima para Especialização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_essencia_talento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nota Máxima para Essência/Talento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_formacao_academica',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nota Máxima para Formação Acadêmica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_idiomas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nota Máxima para Idiomas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_performance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Nota Máxima para Performance'),
            preserve_default=False,
        ),
    ]
