# Generated by Django 2.1 on 2018-09-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0009_auto_20180919_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_idiomas',
            field=models.DecimalField(choices=[(2.0, 'Básico'), (3.0, 'Intermediário'), (5.0, 'Avançado')], decimal_places=2, max_digits=10, verbose_name='Nota Máxima para Idiomas'),
        ),
    ]
