# Generated by Django 2.1 on 2018-09-24 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0011_auto_20180924_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_cursos',
            field=models.CharField(choices=[('1.0', '1 Curso'), ('2.0', '2 Cursos'), ('3.0', '3 Cursos'), ('4.0', '4 Cursos'), ('5.0', '5 Cursos')], max_length=250, verbose_name='Nota Máxima para Cursos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_especializacao',
            field=models.CharField(choices=[('2.0', 'Trancado/Não Possui'), ('3.0', 'Cursando'), ('5.0', 'Concluído')], max_length=250, verbose_name='Nota Máxima para Especialização'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_essencia_talento',
            field=models.CharField(choices=[('1.0', '1 Ponto'), ('2.0', '2 Pontos'), ('3.0', '3 Pontos'), ('4.0', '4 Pontos'), ('5.0', '5 Pontos')], max_length=250, verbose_name='Nota Máxima para Essência/Talento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_formacao_academica',
            field=models.CharField(choices=[('2.0', 'Trancado/Não Possui'), ('3.0', 'Cursando'), ('5.0', 'Concluído')], max_length=250, verbose_name='Nota Máxima para Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_idiomas',
            field=models.CharField(choices=[('2.0', 'Básico'), ('3.0', 'Intermediário'), ('5.0', 'Avançado')], max_length=250, verbose_name='Nota Máxima para Idiomas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_performance',
            field=models.CharField(choices=[('1.0', 'Não atinge o esperado'), ('2.0', 'As vezes atinge'), ('3.0', 'Atinge'), ('4.0', 'As vezes supera'), ('5.0', 'Sempre supera')], max_length=250, verbose_name='Nota Máxima para Performance'),
        ),
    ]
