# Generated by Django 2.1 on 2018-09-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0012_auto_20180924_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisetalento',
            name='nota_experiencia',
            field=models.CharField(default=0, max_length=30, verbose_name='Experiência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='nota_maxima_experiencia',
            field=models.CharField(choices=[('2.0', 'Entre 1 e 2 anos'), ('3.0', 'Entre 3 e 5 anos'), ('5.0', 'Acima de 5 anos')], default=0, max_length=250, verbose_name='Nota Máxima para Experiência'),
            preserve_default=False,
        ),
    ]
