# Generated by Django 2.1 on 2018-09-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0013_auto_20180924_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='accontability',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='aprendizado_desenvolvimento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='atendimento_cliente',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='competitividade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='comportamento',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='comunicacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='criatividade',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='equilibrio_emocional',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='etica',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='excelencia_operacional',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='gestao_mudanca',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='gestao_negocio',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='gestao_pessoas',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='inovacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='negociacao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='protagonismo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='relacionamento_interpessoal',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='solucao_problemas',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='tomada_decisao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='trabalho_equipe',
        ),
    ]
