# Generated by Django 2.1 on 2018-09-25 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0005_auto_20180925_1058'),
        ('perfil', '0014_auto_20180925_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experiencia_profissional.Cargo', verbose_name='Cargo'),
            preserve_default=False,
        ),
    ]
