# Generated by Django 2.1.1 on 2018-10-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0016_auto_20180927_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisetalento',
            name='nota_teste_psicologico',
            field=models.CharField(default=0, max_length=30, verbose_name='Teste Comportamental'),
            preserve_default=False,
        ),
    ]
