# Generated by Django 2.1.1 on 2018-10-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0017_analisetalento_nota_teste_psicologico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigAnaliseTalento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250, verbose_name='Nome')),
                ('maximo_analises', models.IntegerField(verbose_name='Número Máximo de Análises')),
            ],
            options={
                'verbose_name': 'Configuração de Análise de Talento',
                'verbose_name_plural': 'Configurações de Análise de Talento',
            },
        ),
    ]
