# Generated by Django 2.1.1 on 2018-12-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0019_configanalisetalento_quantidade_atual_analises'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='disponivel_pre_analise',
            field=models.BooleanField(default=False, help_text='Habilitar para que o perfil seja pré-analisado para todos os usuários do sistema que preencheremseu cadastro', verbose_name='Perfil disponível para pré-análise?'),
        ),
    ]
