# Generated by Django 2.1.1 on 2018-12-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0020_perfil_disponivel_pre_analise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='disponivel_pre_analise',
            field=models.BooleanField(default=False, help_text='Habilitar para que o perfil seja pré-analisado para todos os usuários do sistema que preencherem o seu cadastro', verbose_name='Perfil disponível para pré-análise?'),
        ),
    ]
