# Generated by Django 2.1.1 on 2018-12-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0021_auto_20181210_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='analisetalento',
            name='pre_analise',
            field=models.BooleanField(default=False, help_text='Esta é uma pré análise?', verbose_name='Pré Análise?'),
        ),
    ]
