# Generated by Django 2.1.1 on 2019-02-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0022_analisetalento_pre_analise'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='beneficios',
            field=models.TextField(blank=True, null=True, verbose_name='Benefícios'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_final',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='projeto',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Salário (R$)'),
        ),
    ]
