# Generated by Django 2.1.1 on 2019-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0024_analisetalento_alocado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisetalento',
            name='alocado',
            field=models.BooleanField(verbose_name='Alocado em projeto?'),
        ),
    ]
