# Generated by Django 2.1.1 on 2019-02-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0025_auto_20190212_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analisetalento',
            name='alocado',
            field=models.BooleanField(default=False, verbose_name='Alocado em projeto?'),
        ),
    ]
