# Generated by Django 2.1.1 on 2019-02-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0026_auto_20190212_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisetalento',
            name='alocado',
        ),
        migrations.AddField(
            model_name='analisetalento',
            name='disponivel_projeto',
            field=models.BooleanField(default=False, verbose_name='Disponível para o projeto?'),
        ),
    ]
