# Generated by Django 2.1.1 on 2019-11-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0028_auto_20190212_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analisetalento',
            name='disponivel_projeto',
        ),
        migrations.RemoveField(
            model_name='analisetalento',
            name='nota_especializacao',
        ),
        migrations.RemoveField(
            model_name='analisetalento',
            name='nota_essencia_talento',
        ),
        migrations.RemoveField(
            model_name='analisetalento',
            name='nota_performance',
        ),
        migrations.RemoveField(
            model_name='analisetalento',
            name='nota_teste_psicologico',
        ),
        migrations.RemoveField(
            model_name='analisetalento',
            name='pre_analise',
        ),
        migrations.RemoveField(
            model_name='analisetalento',
            name='visivel_site',
        ),
        migrations.AddField(
            model_name='analisetalento',
            name='nota_requisitos_tecnicos',
            field=models.CharField(default='', max_length=30, verbose_name='Requisitos Técnicos'),
            preserve_default=False,
        ),
    ]
