# Generated by Django 2.1.1 on 2019-11-06 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0030_auto_20191106_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='nota_requisitos_tecnicos',
            new_name='nota_maxima_requisitos_tecnicos',
        ),
    ]
