# Generated by Django 2.1.1 on 2019-11-06 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0009_auto_20191106_1305'),
        ('perfil', '0031_auto_20191106_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='template_teste_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teste_psicologico.TemplateTestePsicologico', verbose_name='Template de Teste Psicológico'),
        ),
    ]
