# Generated by Django 2.1.1 on 2019-11-08 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0032_perfil_template_teste_psicologico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analisetalento',
            options={'ordering': ['-nota_total'], 'verbose_name': 'Análise de Talento', 'verbose_name_plural': 'Análises de Talentos'},
        ),
    ]
