# Generated by Django 2.1.1 on 2019-11-09 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0033_auto_20191108_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='template_teste_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teste_psicologico.TemplateTestePsicologico', verbose_name='Template de Teste Escrito'),
        ),
    ]
