# Generated by Django 2.1.1 on 2019-11-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0035_perfil_gestor'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nivel_escolaridade_exigido',
            field=models.CharField(blank=True, choices=[('Ensino Médio', 'Ensino Médio'), ('Técnico', 'Técnico'), ('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=50, null=True, verbose_name='Nível de Escolaridade Exigido'),
        ),
    ]
