# Generated by Django 2.1.1 on 2019-11-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0037_auto_20191125_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_experiencia',
            field=models.CharField(choices=[('1.0', 'Até 1 ano'), ('2.0', 'Entre 1 e 2 anos'), ('3.0', 'Entre 2 e 3 anos'), ('4.0', 'Entre 4 e 5 anos'), ('5.0', 'Acima de 5 anos')], max_length=250, verbose_name='Nota Máxima para Experiência'),
        ),
    ]
