# Generated by Django 2.1.1 on 2019-11-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0038_auto_20191125_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='nota_maxima_idiomas',
            field=models.CharField(choices=[('1.0', 'Básico'), ('2.0', 'Básico a Intermediário'), ('3.0', 'Intermediário'), ('4.0', 'Avançado'), ('5.0', 'Fluente/Nativo')], max_length=250, verbose_name='Nota Máxima para Idiomas'),
        ),
    ]
