# Generated by Django 2.1.1 on 2019-11-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0039_auto_20191125_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='visualizar_site',
            field=models.BooleanField(default=False, verbose_name='Disponibilizar no Site?'),
        ),
    ]
