# Generated by Django 2.1.1 on 2019-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0040_perfil_visualizar_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='peso_cursos',
            field=models.IntegerField(default=0, verbose_name='Peso para Cursos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso_experiencia',
            field=models.IntegerField(default=0, verbose_name='Peso para Experiência'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso_formacao_academica',
            field=models.IntegerField(default=0, verbose_name='Peso para Formação Acadêmica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso_idiomas',
            field=models.IntegerField(default=0, verbose_name='Peso para Idiomas'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='perfil',
            name='peso_requisitos_tecnicos',
            field=models.IntegerField(default=0, verbose_name='Peso para Requisitos Técnicos'),
            preserve_default=False,
        ),
    ]
