# Generated by Django 2.1.1 on 2019-11-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0041_auto_20191125_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='peso_cursos',
            field=models.IntegerField(default=1, verbose_name='Peso para Cursos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso_experiencia',
            field=models.IntegerField(default=1, verbose_name='Peso para Experiência'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso_formacao_academica',
            field=models.IntegerField(default=1, verbose_name='Peso para Formação Acadêmica'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso_idiomas',
            field=models.IntegerField(default=1, verbose_name='Peso para Idiomas'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='peso_requisitos_tecnicos',
            field=models.IntegerField(default=1, verbose_name='Peso para Requisitos Técnicos'),
        ),
    ]
