# Generated by Django 2.1.1 on 2019-12-19 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0043_auto_20191219_0536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['nome'], 'verbose_name': 'Vaga', 'verbose_name_plural': 'Vagas'},
        ),
    ]
