# Generated by Django 2.1 on 2018-09-12 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('atribuicoes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoriaCargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('pontos', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='cargo',
            name='categoria_cargo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencia_profissional.CategoriaCargo', verbose_name='Categoria do Cargo'),
        ),
    ]
