# Generated by Django 2.1 on 2018-09-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriacargo',
            options={'verbose_name': 'Categoria de Cargos', 'verbose_name_plural': 'Categorias de Cargos'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
