# Generated by Django 2.1 on 2018-09-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0002_auto_20180912_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='categoria_cargo',
        ),
        migrations.DeleteModel(
            name='CategoriaCargo',
        ),
    ]
