# Generated by Django 2.1 on 2018-09-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0003_auto_20180913_1444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiencia',
            name='nome',
        ),
        migrations.AddField(
            model_name='experiencia',
            name='experiencia',
            field=models.CharField(default='', max_length=150, verbose_name='Experiência'),
            preserve_default=False,
        ),
    ]
