# Generated by Django 2.1 on 2018-09-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0004_auto_20180913_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='accontability',
            field=models.BooleanField(blank=True, default=False, help_text='Comprometimento, resolutividade, entrega, visao de dono.', null=True, verbose_name='Accontability'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='aprendizado_desenvolvimento',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de iniciar novas atividades, novos enfoques e formas de fazer as coisas.', null=True, verbose_name='Aprendizado e Desenvolvimento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='atendimento_cliente',
            field=models.BooleanField(blank=True, default=False, help_text='Descobrir os desejos ocultos dos clientes, investir tempo sobre as necessidades das outras pessoas.', null=True, verbose_name='Atendimento ao Cliente'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='competitividade',
            field=models.BooleanField(blank=True, default=False, help_text='Metas claras e esfocos para se chegar aos objetivos comuns.', null=True, verbose_name='Competitividade'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='comportamento',
            field=models.BooleanField(blank=True, default=False, help_text='Autoconfianca e auto conhecimento.', null=True, verbose_name='Comportamento'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='comunicacao',
            field=models.BooleanField(help_text='Desenvoltura, Coerencia entre discurso e acao, objetividade, capacidade de transmitir ideias e escutar. Capacidade de se comunicar com diferentes tipos de pessoas.', null=True, verbose_name='Comunicação'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='criatividade',
            field=models.BooleanField(blank=True, default=False, help_text='Pensar intuitivamente, pensar e tentar novas formas.', null=True, verbose_name='Criatividade'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='equilibrio_emocional',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de Trabalhar sob Pressao, Resistencia a Frustracao e Maturidade. Autocontrole emocional.', null=True, verbose_name='Equilíbrio Emocional'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='etica',
            field=models.BooleanField(blank=True, default=False, help_text='Transparencia e confiabilidade. Integridade.', null=True, verbose_name='Ética'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='excelencia_operacional',
            field=models.BooleanField(blank=True, default=False, help_text='Ir alem das metas e objetivos (resolutividade), realizar o trablaho com excelencia e produtividade.', null=True, verbose_name='Excelência Operacional'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='gestao_mudanca',
            field=models.BooleanField(blank=True, default=False, help_text='Necessidades constantes de adaptacao, criacao de projetos ou iniciativas para melhorar o desempenho, resultados ou aproveitar oportunidades, gerando mudanças em processos, funções de trabalho, estruturas organizacionais e usos de novas tecnologias.', null=True, verbose_name='Gestão da Mudança'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='gestao_negocio',
            field=models.BooleanField(blank=True, default=False, help_text='Atualizado, tem opiniao sobre onde a empresa esta, para onde vai e realiza previsoes.', null=True, verbose_name='Gestão de Negócio'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='gestao_pessoas',
            field=models.BooleanField(blank=True, default=False, help_text='Delega tarefas, identifica talentos e desenvolve, envolve, trabalha para pessoas e nao para tarefa,tratar de forma personalisada, ampliar a rede de relacionamento. Pedir opiniao.', null=True, verbose_name='Gestão de Pessoas'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='inovacao',
            field=models.BooleanField(blank=True, default=False, help_text='Sair da zona de conforto, possui visao ampla novos focos, novas formas de fazer as coisas.', null=True, verbose_name='Inovação'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='negociacao',
            field=models.BooleanField(help_text='Capacidade de Argumentacao, persuasao, Adm de conflitos, respeito as pessoas e foco no resultado.', null=True, verbose_name='Negociação'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='protagonismo',
            field=models.BooleanField(blank=True, default=False, help_text='Iniciativa, entusiasmo, brilho nos olhos.', null=True, verbose_name='Protagonismo'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='relacionamento_interpessoal',
            field=models.BooleanField(blank=True, default=False, help_text='Domina a cultura da organizacao e otimiza os relacionamentos e mantem bom relacionamento com os fornecedores e clientes.', null=True, verbose_name='Relacionamento Interpessoal'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='solucao_problemas',
            field=models.BooleanField(blank=True, default=False, help_text='Analise critica, Coerencia, Flexibilidade, Improvisacao, adaptacao a mudancas, diversidade.', null=True, verbose_name='Solução de Problemas'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='tomada_decisao',
            field=models.BooleanField(blank=True, default=False, help_text='Analise de informacoes, Compartilha e pede opinioes, riscos.', null=True, verbose_name='Tomada de Decisão'),
        ),
        migrations.AddField(
            model_name='cargo',
            name='trabalho_equipe',
            field=models.BooleanField(blank=True, default=False, help_text='Cooperar, ter a empatia, ou seja a sencibilidade para lidar com os outros, colaborar, escutar e respeitar opinioes, trabalhar em conjunto, aceitar criticas.', null=True, verbose_name='Trabalho em Equipe'),
        ),
    ]
