# Generated by Django 2.1.1 on 2018-10-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0005_auto_20180925_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['id'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
