# Generated by Django 2.1.1 on 2018-10-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0006_auto_20181002_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
