# Generated by Django 2.1.1 on 2018-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0007_auto_20181002_1205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'ordering': ['experiencia'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
