# Generated by Django 2.1.1 on 2018-10-09 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0008_auto_20181004_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaAtuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Área de Atuação')),
            ],
            options={
                'verbose_name': 'Área de Atuação',
                'verbose_name_plural': 'Áreas de Atuação',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='cargo',
            name='area_atuacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experiencia_profissional.AreaAtuacao', verbose_name='Área de Atuação'),
            preserve_default=False,
        ),
    ]
