# Generated by Django 2.1.1 on 2018-10-09 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0009_auto_20181009_1618'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='area_atuacao',
        ),
    ]
