# Generated by Django 2.1.1 on 2018-10-09 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0010_remove_cargo_area_atuacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='area_atuacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='experiencia_profissional.AreaAtuacao', verbose_name='Área de Atuação'),
            preserve_default=False,
        ),
    ]
