# Generated by Django 2.1.1 on 2019-02-11 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0013_merge_20181017_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='superior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiencia_profissional.Cargo'),
        ),
    ]
