# Generated by Django 2.1.1 on 2019-11-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0015_auto_20191106_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='requisitos_tecnicos',
            field=models.ManyToManyField(to='pessoa.RequisitoTecnico', verbose_name='Requisitos Técnicos'),
        ),
    ]
