# Generated by Django 2.2.4 on 2020-01-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0017_auto_20191113_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
    ]
