# Generated by Django 2.2.4 on 2019-08-08 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'ordering': ['estado', 'nome'], 'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
    ]
