# Generated by Django 2.2.4 on 2019-08-08 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190808_1543'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nome'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
    ]
