# Generated by Django 2.2.4 on 2019-08-26 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190808_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='pessoa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Pessoa', verbose_name='Pessoa'),
        ),
    ]
