# Generated by Django 2.2.4 on 2019-09-04 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190826_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroInterno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('arquivo', models.FileField(blank=True, upload_to='registro_interno/', verbose_name='Arquivo')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Registro Interno',
                'verbose_name_plural': 'Registros Internos',
                'ordering': ['-id'],
            },
        ),
    ]
