# Generated by Django 2.2.4 on 2019-10-08 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20190919_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cep',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(help_text='Campo Obrigatório*', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(help_text='Campo Obrigatório*', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='logradouro',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, verbose_name='Logradouro'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='numero',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=10, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.ForeignKey(help_text='Campo Obrigatório*', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=30, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf_cnpj',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=18, unique=True, verbose_name='CPF/CNPJ'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=150, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, verbose_name='Nome'),
        ),
    ]
