# Generated by Django 2.1.1 on 2019-10-09 13:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20191008_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Estado Civil',
                'verbose_name_plural': 'Estados Civis',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='pessoa_ptr',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
    ]
