from django.urls import path
from .views import (
    home, 
    ranking, 
    analise, 
    avaliacao_desempenho, 
    relatorio_genero,
    relatorio_faixa_etaria,
    relatorio_estado_civil,
    relatorio_filhos,
    relatorio_cidade,
    relatorio_curso,
    relatorio_titulacao,
    relatorio_idiomas,
    relatorio_atuacao_profissional,
    relatorio_estatistica_geral,
    relatorio_estatistica_gestor,
    relatorio_estatistica_genero,
    relatorio_estatistica_faixa_etaria,
    relatorio_estatistica_liderados,
)

urlpatterns = [
    path('', home, name="dashboard"),
    path('/ranking/<int:perfil>', ranking, name="ranking"),
    path('/analise/<int:analise>', analise, name="analise"),
    path('/avaliacao_desempenho/', avaliacao_desempenho, name="avaliacao_desempenho"),
    path('/relatorio_genero/', relatorio_genero, name="relatorio_genero"),
    path('/relatorio_faixa_etaria/', relatorio_faixa_etaria, name="relatorio_faixa_etaria"),
    path('/relatorio_estado_civil/', relatorio_estado_civil, name="relatorio_estado_civil"),
    path('/relatorio_filhos/', relatorio_filhos, name="relatorio_filhos"),
    path('/relatorio_cidade/', relatorio_cidade, name="relatorio_cidade"),
    path('/relatorio_curso/', relatorio_curso, name="relatorio_curso"),
    path('/relatorio_titulacao/', relatorio_titulacao, name="relatorio_titulacao"),
    path('/relatorio_idiomas/', relatorio_idiomas, name="relatorio_idiomas"),
    path('/relatorio_atuacao_profissional/', relatorio_atuacao_profissional, name="relatorio_atuacao_profissional"),
    path('/relatorio_estatistica_geral/', relatorio_estatistica_geral, name="relatorio_estatistica_geral"),
    path('/relatorio_estatistica_gestor/', relatorio_estatistica_gestor, name="relatorio_estatistica_gestor"),
    path('/relatorio_estatistica_genero/', relatorio_estatistica_genero, name="relatorio_estatistica_genero"),
    path('/relatorio_estatistica_faixa_etaria/', relatorio_estatistica_faixa_etaria, name="relatorio_estatistica_faixa_etaria"),
    path('/relatorio_estatistica_liderados/', relatorio_estatistica_liderados, name="relatorio_estatistica_liderados"),
]