# Generated by Django 2.1 on 2018-09-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0004_auto_20180918_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='negociacao',
            field=models.NullBooleanField(default=False, help_text='Capacidade de Argumentacao, persuasao, Adm de conflitos, respeito as pessoas e foco no resultado.', verbose_name='Negociação'),
        ),
    ]
