# Generated by Django 2.1 on 2018-09-18 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0005_auto_20180918_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='negociacao',
            field=models.BooleanField(help_text='Capacidade de Argumentacao, persuasao, Adm de conflitos, respeito as pessoas e foco no resultado.', null=True, verbose_name='Negociação'),
        ),
    ]
