# Generated by Django 2.1 on 2018-09-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0006_auto_20180918_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienciaprofissional',
            options={'verbose_name': 'Performance', 'verbose_name_plural': 'Performances'},
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cargo_atual',
        ),
    ]
