# Generated by Django 2.1 on 2018-09-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0007_auto_20180918_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='idioma',
            field=models.ManyToManyField(blank=True, to='formacao.Idioma'),
        ),
    ]
