# Generated by Django 2.1.1 on 2018-10-05 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0010_auto_20181001_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='descricao',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
