# Generated by Django 2.1.1 on 2018-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0011_auto_20181005_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacaoacademica',
            name='certificado',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
