# Generated by Django 2.1.1 on 2018-10-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0012_formacaoacademica_certificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='certificado',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='especializacao',
            name='certificado',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
