# Generated by Django 2.1.1 on 2018-10-10 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0009_auto_20181010_0845'),
        ('pessoa', '0013_auto_20181005_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='especializacao',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formacao.Curso', verbose_name='Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='formacao.Curso', verbose_name='Curso'),
            preserve_default=False,
        ),
    ]
