# Generated by Django 2.1.1 on 2018-10-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0014_auto_20181010_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='comunicacao',
            field=models.BooleanField(help_text='Capacidade de se comunicar com diferentes tipos de pessoas, transmitir ideias com desenvoltura, coerência entre discurso e ação, objetividade, explicando assuntos complexos, fazendo com que os outros captem a mensagem e possuir escuta ativa, considerando a opinião do outro.', null=True, verbose_name='Comunicação'),
        ),
    ]
