# Generated by Django 2.1.1 on 2018-10-16 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0014_auto_20181010_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='accontability',
            field=models.BooleanField(blank=True, default=False, help_text='Comprometimento, resolutividade como dono da função  que desempenha dando importância ao  que faz, como faz, por qual motivo faz, quanto gasta e o que vai fazer a seguir.', null=True, verbose_name='Accontability'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='aprendizado_desenvolvimento',
            field=models.BooleanField(blank=True, default=False, help_text='Estar constantemente em auto-avaliação para levantar necessidades de aprendizado, identificando objetivos, obstáculos, planejamento de açoes e recursos e prazos necessarios para o desenvolvimento, avaliando o progresso do novo comportamento, raciocinio ou emoção, e o reflexo no resultado. Aberto, aprendendo novas formas de pensar, agir, se relacionar e fazer as coisas.', null=True, verbose_name='Aprendizado e Desenvolvimento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='atendimento_cliente',
            field=models.BooleanField(blank=True, default=False, help_text='Manter o mais alto padrão em termos de qualidade e serviços a partir da perspectiva do cliente. Com uma visão de que tudo começa e termina no cliente. Tendo em sua expectativa o atendimento as necessidades do cliente.P ossibilitando a melhor experiência que seu cliente precise.', null=True, verbose_name='Atendimento ao Cliente'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='competitividade',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de cumprir a missão com êxito maior que outras organizações competidoras. Suprindo as necessidades e expectativas no seu mercado atuante. Obtendo resultados iguais ou superiores. Melhorando o aproveitamento de recursos e outros pressupostos, incrementando e agregando valor e alterando para novas estratégias e modelos de negócios.', null=True, verbose_name='Competitividade e Produtividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='comportamento',
            field=models.BooleanField(blank=True, default=False, help_text='Se comportar de forma adequada, nos papeis sociais, empregando de forma consciente as emoções, pensamentos, qualidades e capacidades de forma harmoniosa ao ambiente, na realidade que o permeia, sempre melhorando, aprendendo e evoluindo  pontos fracos.  Se mantendo, sem se abalar mediante obstáculos e adversidades.', null=True, verbose_name='Comportamento'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='comunicacao',
            field=models.BooleanField(help_text='Capacidade de se comunicar com diferentes tipos de pessoas, transmitir ideias com desenvoltura, coerência entre discurso e ação, objetividade, explicando assuntos complexos, fazendo com que os outros captem a mensagem e possuir escuta ativa, considerando a opinião do outro.', null=True, verbose_name='Comunicação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='criatividade',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de integrar o pensamento a um contexto, analisando, sintetizando, associando e criando combinações que produzam novas formas de ideias, produtos, soluções de problemas, de forma única e original. Possíveis de serem aplicadas na prática agregando valor.', null=True, verbose_name='Criatividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='equilibrio_emocional',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de saber lidar e empregar as emoções com situações inesperadas, reagindo de forma positiva a elas. Se auto observando, eliminando questões desnecessárias. Transformando as respostas intempestivas em ações e respostas guiadas pelo autocontrole. Se concentrando no aqui e agora sem misturar emoções de experiências passadas e sem pensamentos ansiosos em relação ao futuro.', null=True, verbose_name='Equilíbrio Emocional'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='etica',
            field=models.BooleanField(blank=True, default=False, help_text='Ter consciência do conjunto de regras relacionadas a valores e conceitos morais, mediante o ambiente e pessoas, representados em suas condutas. Sendo em seus comportamentos honesto, humilde, tolerante, flexível e disposto.', null=True, verbose_name='Ética'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='excelencia_operacional',
            field=models.BooleanField(blank=True, default=False, help_text='Alcançar a satisfação, ou seja a Excelência  necessária para que o trabalho, produto, processo e/ou serviço, entregue no momento certo, de acordo com as especificações previamente acordadas, que seja fácil, funcione, que não tenha problemas (defeitos) no curto prazo e que traga os benefícios prometidos e esperados.', null=True, verbose_name='Excelência Operacional'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='gestao_mudanca',
            field=models.BooleanField(blank=True, default=False, help_text='Fazer escolhas conscientes a respeito do comportamento, considerando o que é importante, suas capacidades e consequencias. Ajustando quando necessário para produzir determinados resultados e mudanças no ambiente. (contexto, papeis, responsabilidades e pessoas). Transitando de um modelo e passado para um novo estado, futuro desejado. Com consciencia da razão e da necessidade de mudança. Gerenciando os possiveis problemas e reaçoes que podem sugir. Sem resistir.', null=True, verbose_name='Gestão da Mudança'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='gestao_negocio',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de compreender a missão da organização, o seu objetivo global. Estabelecer definições do que deve ser feito para cumprir a missão. Compreendendo as forças e fraquezas, oportunidades e ameaças. Analisar a viabilidade do negócio e estabelecer estratégias. Corrigir os objetivos, analisar os problemas e definir fatores críticos, para preparar e implementar planos monitorando seus resultados.', null=True, verbose_name='Gestão de Negócio'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='gestao_pessoas',
            field=models.BooleanField(blank=True, default=False, help_text='Conseguir definir a quantidade de recursos e os niveis necessarios, de acordo com as necessidades de realização de funções. Dar a direção com um estilo de liderança que encoraje o crescimento, adequado a cada perfil e situação. Garantindo que as tarefas sejam realizadas, mantendo um relacionamento eficaz, capacitando e desenvolvendo suas equipes.', null=True, verbose_name='Gestão de Pessoas'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='inovacao',
            field=models.BooleanField(blank=True, default=False, help_text='Criar um desafio mediante o que não se faz ainda, como uma oportunidade nova. Assumindo riscos. Buscando o inédito e original, promovendo mudanças. Analisando o que ocorre, quem somos, o contexto que estamos, nosso papel, alterando atitudes e a realidade.', null=True, verbose_name='Inovação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='negociacao',
            field=models.BooleanField(help_text='Capacidade de definir claramente a perspectiva e objetivos que se pretende alcançar. Conseguindo retirar o maior número de informações que são importantes neste processo, colocando-se no lugar do outro, descobrindo seus interesses. Desenvolvendo e argumentando com persuasão, opções, alternativas e possibilidades de consolidações com consenso e acordos.', null=True, verbose_name='Negociação'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='protagonismo',
            field=models.BooleanField(blank=True, default=False, help_text='Qualidade da pessoa que se destaca em qualquer situação desempenhando um papel principal, mais importante que os demais, buscando a melhor estratégia para o melhor resultado. Transformando ideias em ações concretas, sempre ativo, antecipando-se, vigilante e ativo.', null=True, verbose_name='Protagonismo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='relacionamento_interpessoal',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de criar vinculos com as pessoas, tendo empatia, mantendo o respeito. Desenvolvendo uma comunciação efetiva. Respeitando a diversidade de credo, origem, cor, orientação sexual, nacionalidade, time, religião, cultura, ideologia política e ou ideias. Estabelecendo uma rede de pessoas.', null=True, verbose_name='Relacionamento Interpessoal'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='solucao_problemas',
            field=models.BooleanField(blank=True, default=False, help_text='Capacidade de identificação e priorização de problemas, com um pensamento analítico, decompondo em partes mais simples as características dos problemas, para determinar suas causas, desenvolvendo e implementando planos e ações corretivas e preventivas para eliminar causas de problemas, confirmando a eficácia das ações.', null=True, verbose_name='Análise e Solução de Problemas'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='tomada_decisao',
            field=models.BooleanField(blank=True, default=False, help_text='Tomar decisões no tempo adequado. Estando preparado para situaçoes que possam vir de consequencia, usando uma capacidade analítica  para se chegar a conclusões rápidas, sem tendenciar a suposições e ignorar fatos. Aproveitando experiencias passadas e melhores abordagens, considerando mudanças. Estabelecendo claramente o objetivo, os critérios de julgamento, as causas, desenvolvendo e testando hipóteses, soluções e alternativas.', null=True, verbose_name='Tomada de Decisão'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='trabalho_equipe',
            field=models.BooleanField(blank=True, default=False, help_text='Complementar com uma equipe em habilidades e experiências para um bom desempenho. Com um conjunto de valores que encorajam comportmaentos como saber ouvir e responder de forma cooperativa, oferecendo  apoio e reconhecimento a quem dele precisar. E uma atmosfera confortavel, com objetivos aceitos por todos, discussões livres, onde uns ouvm os outros, com decisões por consenso, com libertade de expressão e atribuiçõs bem claras e aceitas.', null=True, verbose_name='Trabalho em Equipe'),
        ),
    ]
