# Generated by Django 2.1.1 on 2018-10-17 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0015_auto_20181010_1924'),
        ('pessoa', '0015_auto_20181016_1513'),
    ]

    operations = [
    ]
