# Generated by Django 2.1.1 on 2019-01-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0019_pessoa_proposito'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pessoa'),
        ),
    ]
