# Generated by Django 2.1.1 on 2019-01-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0020_pessoa_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='pessoa/static/images', verbose_name='Foto'),
        ),
    ]
