# Generated by Django 2.1.1 on 2019-01-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0021_auto_20190114_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(blank=True, upload_to='perfil', verbose_name='Foto'),
        ),
    ]
