# Generated by Django 2.1.1 on 2019-01-15 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0022_auto_20190114_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='video',
            field=models.FileField(blank=True, upload_to='video', verbose_name='Vídeo'),
        ),
    ]
