# Generated by Django 2.1.1 on 2019-02-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0024_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_nascimento',
        ),
    ]
