# Generated by Django 2.1.1 on 2019-02-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0025_auto_20190228_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='instituicao',
        ),
    ]
