# Generated by Django 2.1.1 on 2019-02-28 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0026_auto_20190228_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacaoacademica',
            name='ano_formacao',
        ),
        migrations.RemoveField(
            model_name='formacaoacademica',
            name='instituicao',
        ),
    ]
