# Generated by Django 2.1.1 on 2019-02-28 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0027_auto_20190228_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='carga_horaria',
        ),
        migrations.RemoveField(
            model_name='curso',
            name='instituicao',
        ),
        migrations.RemoveField(
            model_name='especializacao',
            name='ano_formacao',
        ),
        migrations.RemoveField(
            model_name='especializacao',
            name='instituicao',
        ),
    ]
