# Generated by Django 2.1.1 on 2019-03-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0028_auto_20190228_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='curriculo', verbose_name='Currículo'),
        ),
    ]
