# Generated by Django 2.1.1 on 2019-10-09 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20191009_1002'),
        ('pessoa', '0029_pessoa_curriculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cidade',
            field=models.ForeignKey(help_text='Campo Obrigatório*', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Cidade', verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='disponibilidade_viajar',
            field=models.BooleanField(default=False, verbose_name='Disponibilidade para Viajar?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='documento',
            field=models.FileField(blank=True, upload_to='documentos/', verbose_name='CPF Digitalizado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='estado',
            field=models.ForeignKey(help_text='Campo Obrigatório*', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='ja_trabalhou',
            field=models.BooleanField(default=False, verbose_name='Já trabalhou na empresa?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='logradouro',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Endereço Residencial'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pretensao_salarial',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Campo Obrigatório*', max_digits=8, verbose_name='Pretensão Salarial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefone 2'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='curriculo',
            field=models.FileField(blank=True, upload_to='curriculos/', verbose_name='Currículo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=250, verbose_name='Nome Completo'),
        ),
    ]
