# Generated by Django 2.1.1 on 2019-10-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0031_pessoa_estado_civil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(help_text='Campo Obrigatório*', max_length=100, verbose_name='E-mail'),
        ),
    ]
