# Generated by Django 2.1.1 on 2019-10-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0032_auto_20191009_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='disponibilidade_viajar',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Disponibilidade para Viajar?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ja_trabalhou',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, verbose_name='Já trabalhou na empresa?'),
        ),
    ]
