# Generated by Django 2.1.1 on 2019-10-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0033_auto_20191009_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='nome_projeto',
            field=models.CharField(blank=True, max_length=80, verbose_name='Projeto'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='quando_trabalhou',
            field=models.DateField(blank=True, null=True, verbose_name='Quando Trabalhou'),
        ),
    ]
