# Generated by Django 2.1.1 on 2019-10-09 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0034_auto_20191009_1455'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='nome_projeto',
            new_name='projeto_trabalhou',
        ),
    ]
