# Generated by Django 2.1.1 on 2019-10-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0035_auto_20191009_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='link_perfil_linkedin',
            field=models.CharField(blank=True, max_length=80, verbose_name='Link perfil do Linkedin'),
        ),
    ]
