# Generated by Django 2.1.1 on 2019-10-15 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0009_auto_20181010_0845'),
        ('pessoa', '0036_pessoa_link_perfil_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formacaoacademica',
            name='formacao_academica',
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formacao.Instituicao', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='nivel_escolaridade',
            field=models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Técnico', 'Técnico'), ('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], default='Ensino Médio', max_length=50, verbose_name='Nível de Escolaridade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formacaoacademica',
            name='situacao',
            field=models.CharField(choices=[('Concluído', 'Concluído'), ('Cursando', 'Cursando'), ('Trancado', 'Trancado')], default='Concluído', max_length=50, verbose_name='Situação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='certificado',
            field=models.FileField(blank=True, upload_to='', verbose_name='Mídia'),
        ),
    ]
