# Generated by Django 2.1.1 on 2019-10-15 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0009_auto_20181010_0845'),
        ('pessoa', '0037_auto_20191015_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='carga_horaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formacao.CargaHoraria', verbose_name='Carga Horária'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='curso',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='formacao.Instituicao', verbose_name='Instituição'),
        ),
    ]
