# Generated by Django 2.1.1 on 2019-10-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0038_auto_20191015_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especializacao',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='especializacao',
            name='especializacao',
        ),
        migrations.RemoveField(
            model_name='especializacao',
            name='pessoa',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='idioma',
        ),
        migrations.DeleteModel(
            name='Especializacao',
        ),
    ]
