# Generated by Django 2.1.1 on 2019-10-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0039_auto_20191015_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experienciaprofissional',
            name='performance',
        ),
    ]
