# Generated by Django 2.1.1 on 2019-10-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0040_remove_experienciaprofissional_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaprofissional',
            name='data_inicio',
            field=models.DateField(null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='experienciaprofissional',
            name='empresa',
            field=models.CharField(default='', max_length=150, verbose_name='Empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='tempo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencia_profissional.Experiencia', verbose_name='Tempo de Permanência'),
        ),
    ]
