# Generated by Django 2.1.1 on 2019-10-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0042_auto_20191015_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experienciaprofissional',
            name='tempo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='experiencia_profissional.Experiencia', verbose_name='Tempo de Permanência'),
        ),
    ]
