# Generated by Django 2.1.1 on 2019-10-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0043_auto_20191015_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='instituicao',
            field=models.CharField(max_length=150, null=True, verbose_name='Instituição'),
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='certificado',
            field=models.FileField(blank=True, upload_to='', verbose_name='Certificado'),
        ),
    ]
