# Generated by Django 2.1.1 on 2019-10-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0044_auto_20191028_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.CharField(max_length=150, null=True, verbose_name='Carga Horária'),
        ),
    ]
