# Generated by Django 2.1.1 on 2019-10-28 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0045_auto_20191028_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacaoacademica',
            name='instituicao',
            field=models.CharField(max_length=150, null=True, verbose_name='Instituição'),
        ),
    ]
