# Generated by Django 2.1.1 on 2019-10-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0047_midia'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='link',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='midia',
            name='titulo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Título'),
        ),
    ]
