# Generated by Django 2.1.1 on 2019-10-31 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0049_midia_data_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='accontability',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='aprendizado_desenvolvimento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='atendimento_cliente',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='competitividade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='comportamento',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='comunicacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='criatividade',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='equilibrio_emocional',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='etica',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='excelencia_operacional',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='gestao_mudanca',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='gestao_negocio',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='gestao_pessoas',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='inovacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='negociacao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='proposito',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='protagonismo',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='relacionamento_interpessoal',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='solucao_problemas',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tomada_decisao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='trabalho_equipe',
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Estado'),
        ),
    ]
