# Generated by Django 2.1.1 on 2019-10-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0050_auto_20191031_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='telefone2',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=30, verbose_name='Celular'),
        ),
    ]
