# Generated by Django 2.1.1 on 2019-11-01 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia_profissional', '0014_cargo_superior'),
        ('pessoa', '0053_auto_20191101_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='experiencia_profissional.Cargo', verbose_name='Cargo na Empresa'),
        ),
    ]
