# Generated by Django 2.1.1 on 2019-11-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0055_filho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cor',
            field=models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Morena', 'Morena'), ('Parda', 'Parda'), ('Negra', 'Negra')], max_length=50, null=True, verbose_name='Cor'),
        ),
    ]
