# Generated by Django 2.1.1 on 2019-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0056_auto_20191102_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='habilidades_tecnicas',
            field=models.TextField(blank=True, null=True, verbose_name='Habilidades Técnicas'),
        ),
    ]
