# Generated by Django 2.1.1 on 2019-11-05 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0057_pessoa_habilidades_tecnicas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequisitoTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Requisito Técnico',
                'verbose_name_plural': 'Requisitos Técnicos',
            },
        ),
    ]
