# Generated by Django 2.1.1 on 2019-11-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0058_requisitotecnico'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='requisitos_tecnicos',
            field=models.ManyToManyField(blank=True, null=True, to='pessoa.RequisitoTecnico', verbose_name='Requisitos Técnicos'),
        ),
    ]
