# Generated by Django 2.1.1 on 2019-11-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0059_pessoa_requisitos_tecnicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MAS', 'Masculino'), ('FEM', 'Feminino')], max_length=3, null=True, verbose_name='Sexo'),
        ),
    ]
