# Generated by Django 2.1.1 on 2019-11-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0060_auto_20191106_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='requisitos_tecnicos',
            field=models.ManyToManyField(blank=True, to='pessoa.RequisitoTecnico', verbose_name='Requisitos Técnicos'),
        ),
    ]
