# Generated by Django 2.1.1 on 2019-11-25 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0061_auto_20191107_1235'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experienciaprofissional',
            options={'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
    ]
