# Generated by Django 2.1.1 on 2019-12-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0062_auto_20191125_0907'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaprofissional',
            name='trabalho_atual',
            field=models.BooleanField(default=False, verbose_name='Trabalho Atual?'),
        ),
    ]
