# Generated by Django 2.1.1 on 2019-12-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0063_experienciaprofissional_trabalho_atual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='curriculo',
            field=models.FileField(blank=True, null=True, upload_to='curriculos/', verbose_name='Currículo'),
        ),
    ]
