# Generated by Django 2.1.1 on 2019-12-19 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0064_auto_20191216_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requisitotecnico',
            options={'ordering': ['nome'], 'verbose_name': 'Requisito Técnico', 'verbose_name_plural': 'Requisitos Técnicos'},
        ),
    ]
