# Generated by Django 2.1.1 on 2019-12-20 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0066_pessoa_gestor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='bairro',
            field=models.CharField(blank=True, help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cep',
            field=models.CharField(blank=True, help_text='Campo Obrigatório*', max_length=9, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cidade',
            field=models.CharField(blank=True, help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(blank=True, help_text='Campo Obrigatório*', max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='disponibilidade_viajar',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Disponibilidade para Viajar?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='email',
            field=models.EmailField(blank=True, help_text='Campo Obrigatório*', max_length=100, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado',
            field=models.CharField(blank=True, help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='estado_civil',
            field=models.ForeignKey(blank=True, help_text='Campo Obrigatório*', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.EstadoCivil', verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='ja_trabalhou',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Já trabalhou na empresa?'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='logradouro',
            field=models.CharField(blank=True, help_text='Campo Obrigatório*', max_length=200, null=True, verbose_name='Endereço Residencial'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='pretensao_salarial',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Campo Obrigatório*', max_digits=8, null=True, verbose_name='Pretensão Salarial'),
        ),
    ]
