# Generated by Django 2.2.4 on 2020-01-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0067_auto_20191220_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='atividades_relevantes',
            field=models.TextField(blank=True, null=True, verbose_name='Descreva as 5 atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes',
            field=models.TextField(blank=True, null=True, verbose_name='Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes',
            field=models.TextField(blank=True, null=True, verbose_name='Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
    ]
