# Generated by Django 2.2.4 on 2020-01-07 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_filial_grupo'),
        ('pessoa', '0068_auto_20200103_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='chave_integracao',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Chave Integração'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='filial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Filial', verbose_name='Filial'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Grupo', verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula'),
        ),
    ]
