# Generated by Django 2.2.4 on 2020-01-07 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0069_auto_20200107_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='casamento_anexo',
            field=models.FileField(blank=True, upload_to='documentos/', verbose_name='Certidão de Casamento Digitalizada'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='nascimento_anexo',
            field=models.FileField(blank=True, upload_to='documentos/', verbose_name='Certidão de Nascimento Digitalizada'),
        ),
    ]
