# Generated by Django 2.2.4 on 2020-01-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0070_auto_20200107_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='filho',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
