# Generated by Django 2.2.4 on 2020-01-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0071_filho_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='curso',
            field=models.CharField(max_length=150, null=True, verbose_name='Curso'),
        ),
    ]
