# Generated by Django 2.2.4 on 2020-01-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0072_auto_20200112_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='atividades_relevantes',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atividades_relevantes1',
            field=models.TextField(blank=True, null=True, verbose_name='1 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atividades_relevantes2',
            field=models.TextField(blank=True, null=True, verbose_name='2 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atividades_relevantes3',
            field=models.TextField(blank=True, null=True, verbose_name='3 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atividades_relevantes4',
            field=models.TextField(blank=True, null=True, verbose_name='4 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='atividades_relevantes5',
            field=models.TextField(blank=True, null=True, verbose_name='5 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes1',
            field=models.TextField(blank=True, null=True, verbose_name='1 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes2',
            field=models.TextField(blank=True, null=True, verbose_name='2 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes3',
            field=models.TextField(blank=True, null=True, verbose_name='3 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes4',
            field=models.TextField(blank=True, null=True, verbose_name='4 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes5',
            field=models.TextField(blank=True, null=True, verbose_name='5 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes1',
            field=models.TextField(blank=True, null=True, verbose_name='1 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes2',
            field=models.TextField(blank=True, null=True, verbose_name='2 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes3',
            field=models.TextField(blank=True, null=True, verbose_name='3 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes4',
            field=models.TextField(blank=True, null=True, verbose_name='4 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes5',
            field=models.TextField(blank=True, null=True, verbose_name='5 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
    ]
