# Generated by Django 2.2.4 on 2020-01-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0074_auto_20200113_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='projeto_trabalhou',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Projeto'),
        ),
    ]
