# Generated by Django 2.2.4 on 2020-01-13 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0075_auto_20200113_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='link_perfil_linkedin',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Link perfil do Linkedin'),
        ),
    ]
