# Generated by Django 2.2.4 on 2020-01-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0076_auto_20200113_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='formacaoacademica',
            name='outro_curso',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Outro Curso'),
        ),
    ]
