# Generated by Django 2.2.4 on 2020-01-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0077_formacaoacademica_outro_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='filho',
            name='cpf_anexo',
            field=models.FileField(blank=True, upload_to='documentos/', verbose_name='CPF Digitalizado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='pis_numero',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número do PIS'),
        ),
    ]
