# Generated by Django 2.2.4 on 2020-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0078_auto_20200115_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciaprofissional',
            name='outro_cargo',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Outro Cargo'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='divorcio_anexo',
            field=models.FileField(blank=True, upload_to='documentos/', verbose_name='Divorcio Digitalizado'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='numero_endereco',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número'),
        ),
    ]
