# Generated by Django 2.2.4 on 2020-01-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0079_auto_20200120_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='atividades_relevantes1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='atividades_relevantes2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='atividades_relevantes3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='atividades_relevantes4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='4 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='atividades_relevantes5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='5 - Descreva as atividades mais relevantes de sua atuação na empresa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='4 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_qualitativa_atividades_relevantes5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='5 - Como você mede ou medirá QUALITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes1',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='1 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes2',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='2 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes3',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='3 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes4',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='4 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='medicao_quantitativa_atividades_relevantes5',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='5 - Como você mede ou medirá QUANTITATIVAMENTE cada atividade'),
        ),
    ]
