# Generated by Django 2.2.4 on 2020-01-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0080_auto_20200120_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='aceite_politica_privacidade',
            field=models.BooleanField(default=False, verbose_name='Aceite da Política de Privacidade'),
        ),
    ]
