# Generated by Django 2.2.4 on 2020-01-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0081_pessoa_aceite_politica_privacidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='aceite_politica_privacidade',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Aceite da Política de Privacidade'),
        ),
    ]
