# Generated by Django 2.2.4 on 2020-01-29 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0083_auto_20200122_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='experienciaprofissional',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='formacaoacademica',
            options={'ordering': ['data_inicio'], 'verbose_name': 'Formação Acadêmica', 'verbose_name_plural': 'Formações Acadêmicas'},
        ),
        migrations.AlterField(
            model_name='formacaoacademica',
            name='nivel_escolaridade',
            field=models.CharField(choices=[('Ensino Fundamental', 'Ensino Fundamental'), ('Ensino Médio', 'Ensino Médio'), ('Técnico', 'Técnico'), ('Graduação', 'Graduação'), ('Especialização', 'Especialização'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=50, verbose_name='Nível de Escolaridade'),
        ),
    ]
