# Generated by Django 2.2.4 on 2020-01-31 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0085_auto_20200129_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='experienciaprofissional',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Experiência', 'verbose_name_plural': 'Experiências'},
        ),
        migrations.AlterModelOptions(
            name='formacaoacademica',
            options={'ordering': ['-data_inicio'], 'verbose_name': 'Formação Acadêmica', 'verbose_name_plural': 'Formações Acadêmicas'},
        ),
    ]
