# Generated by Django 2.2.4 on 2020-02-04 13:02

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0088_auto_20200204_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInherited',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
