# Generated by Django 2.2.4 on 2020-02-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0089_userinherited'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInherited',
        ),
    ]
