# Generated by Django 2.2.4 on 2020-02-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0090_delete_userinherited'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='data_contratacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Contratação'),
        ),
    ]
