# Generated by Django 2.2.4 on 2020-02-05 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0091_pessoa_data_contratacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_contratacao',
        ),
    ]
