# Generated by Django 2.2.4 on 2020-02-10 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0093_pessoa_data_contratacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pares_avaliadores',
            field=models.ManyToManyField(blank=True, null=True, to='pessoa.Pessoa', verbose_name='Pares Avaliadores'),
        ),
    ]
