# Generated by Django 2.1.1 on 2019-12-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0002_competencia_explicativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemCompetencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('RA', 'Raramente'), ('OC', 'Ocasionalmente'), ('CO', 'Constantemente'), ('EX', 'Exacerbadamente')], max_length=2, verbose_name='Resposta')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao_avaliacao_desempenho.Competencia', verbose_name='Competência')),
            ],
            options={
                'verbose_name': 'Item de Competência',
                'verbose_name_plural': 'Itens de Competências',
                'ordering': ['competencia'],
            },
        ),
        migrations.CreateModel(
            name='ItemPotencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(choices=[('NA', 'Avaliação não apropriada no momento (menos de 6 meses na empresa)'), ('R-', 'Não satisfatório, devendo ser fruto de análise para atividade de menor complexidade ou desligamento'), ('R', 'Situação estável'), ('R+', 'Capacidade para crescimento horizontal, atividades mais complexas'), ('AP', 'Potencial para crescimento vertical')], max_length=2, verbose_name='Resposta')),
                ('potencial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configuracao_avaliacao_desempenho.Potencial', verbose_name='Potencial')),
            ],
            options={
                'verbose_name': 'Item de Potencial',
                'verbose_name_plural': 'Itens de Potenciais',
                'ordering': ['potencial'],
            },
        ),
    ]
