# Generated by Django 2.1.1 on 2019-12-11 17:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0063_experienciaprofissional_trabalho_atual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao_desempenho', '0003_auto_20191211_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDesempenho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondido', models.BooleanField(default=False, verbose_name='Avaliação Respondida')),
                ('data_avaliacao', models.DateField(blank=True, null=True, verbose_name='Data')),
                ('nota_competencia', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Competência')),
                ('nota_meta', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Meta')),
                ('nota_potencial', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Nota de Potencial')),
                ('data_criacao', models.DateTimeField(default=datetime.datetime.now, verbose_name='Data de Criação')),
                ('avaliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Avaliação de Desempenho',
                'verbose_name_plural': 'Avaliações de Desempenho',
            },
        ),
    ]
