# Generated by Django 2.1.1 on 2019-12-11 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0004_avaliacaodesempenho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaodesempenho',
            old_name='data_avaliacao',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='avaliacaodesempenho',
            old_name='respondido',
            new_name='respondida',
        ),
    ]
