# Generated by Django 2.1.1 on 2019-12-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0005_auto_20191211_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcompetencia',
            name='avaliacao_desempenho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao_desempenho.AvaliacaoDesempenho', verbose_name='Avaliação de Desempenho'),
        ),
    ]
