# Generated by Django 2.1.1 on 2019-12-11 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0006_itemcompetencia_avaliacao_desempenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempotencial',
            name='avaliacao_desempenho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao_desempenho.AvaliacaoDesempenho', verbose_name='Avaliação de Desempenho'),
        ),
    ]
