# Generated by Django 2.1.1 on 2019-12-11 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0008_auto_20191211_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.TextField(verbose_name='Meta')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('explicativo', models.TextField(blank=True, null=True, verbose_name='Explicativo')),
                ('resultado_esperado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Resultado Esperado')),
                ('forma_medicao', models.CharField(choices=[('QT', 'Quantitativa'), ('QA', 'Qualitativa')], max_length=2, verbose_name='Forma de Medição')),
                ('resposta', models.CharField(blank=True, max_length=2, null=True, verbose_name='Resposta')),
                ('nota', models.IntegerField(blank=True, null=True, verbose_name='Nota')),
                ('avaliacao_desempenho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao_desempenho.AvaliacaoDesempenho', verbose_name='Avaliação de Desempenho')),
            ],
            options={
                'verbose_name': 'Item de Meta',
                'verbose_name_plural': 'Itens de Metas',
            },
        ),
    ]
