# Generated by Django 2.1.1 on 2019-12-12 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0009_itemmeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='tipo_avaliacao',
            field=models.CharField(choices=[('A', 'Autoavaliação'), ('G', 'Gestor'), ('S', 'Subordinado'), ('P', 'Pares')], max_length=1, null=True, verbose_name='Tipo de Avaliação'),
        ),
    ]
