# Generated by Django 2.1.1 on 2019-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0010_avaliacaodesempenho_tipo_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='tipo_avaliacao',
            field=models.CharField(choices=[('autoavaliacao', 'Autoavaliação'), ('gestor', 'Gestor'), ('subordinado', 'Subordinado'), ('par', 'Par')], max_length=15, null=True, verbose_name='Tipo de Avaliação'),
        ),
    ]
