# Generated by Django 2.1.1 on 2019-12-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0011_auto_20191212_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmeta',
            name='atingimento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Atingimento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemmeta',
            name='resultado_atingido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Resultado Atingido'),
            preserve_default=False,
        ),
    ]
