# Generated by Django 2.1.1 on 2019-12-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0012_auto_20191213_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='resposta_potencial',
            field=models.CharField(blank=True, choices=[('NA', 'Avaliação não apropriada no momento (menos de 6 meses na empresa)'), ('R-', 'Não satisfatório, devendo ser fruto de análise para atividade de menor complexidade ou desligamento'), ('R', 'Situação estável'), ('R+', 'Capacidade para crescimento horizontal, atividades mais complexas'), ('AP', 'Potencial para crescimento vertical')], max_length=2, null=True, verbose_name='Resposta de Potencial'),
        ),
    ]
