# Generated by Django 2.2.4 on 2020-01-21 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0015_remove_avaliacaodesempenho_nota_competencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaodesempenho',
            name='resultado_comite',
            field=models.CharField(blank=True, choices=[('TRA', 'Transição'), ('ATI', 'Atenção Imediata'), ('DES', 'Em Desenvolvimento'), ('EST', 'Estável'), ('CON', 'Consistente'), ('SUC', 'Sucessor')], max_length=3, null=True, verbose_name='Resultado Comitê'),
        ),
    ]
