# Generated by Django 2.2.4 on 2020-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0016_avaliacaodesempenho_resultado_comite'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupoavaliacaodesempenho',
            name='ja_gerado',
            field=models.BooleanField(default=False, verbose_name='Avaliações já Geradas'),
        ),
    ]
