# Generated by Django 2.2.4 on 2020-04-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0018_avaliacaodesempenho_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaodesempenho',
            name='resposta_potencial',
            field=models.CharField(blank=True, choices=[('NA', 'NA / Avaliação não apropriada no momento (menos de 6 meses na empresa)'), ('R-', 'R- / Não satisfatório, devendo ser fruto de análise para atividade de menor complexidade ou desligamento'), ('R', 'R / Situação estável'), ('R+', 'R+ / Capacidade para crescimento horizontal, atividades mais complexas'), ('AP', 'AP / Potencial para crescimento vertical')], max_length=2, null=True, verbose_name='Resposta de Potencial'),
        ),
    ]
