# Generated by Django 2.1.1 on 2018-10-16 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pessoa', '0015_auto_20181016_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afirmativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afirmativa', models.TextField(verbose_name='Afirmativa')),
                ('resposta_esperada', models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('I', 'Discordo Totalmente')], max_length=1, verbose_name='Resposta')),
                ('ordem', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Afirmativa',
                'verbose_name_plural': 'Afirmativas',
                'ordering': ['afirmativa'],
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('afirmativa', models.TextField(verbose_name='Afirmativa')),
                ('resposta_esperada', models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('I', 'Discordo Totalmente')], max_length=1, verbose_name='Resposta')),
                ('resposta', models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('I', 'Discordo Totalmente')], max_length=1, verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['afirmativa'],
            },
        ),
        migrations.CreateModel(
            name='TestePsicologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontuacao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Pontuação')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Teste Psicológico',
                'verbose_name_plural': 'Testes Psicológicos',
                'ordering': ['pessoa'],
            },
        ),
        migrations.AddField(
            model_name='resposta',
            name='teste_psicologico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_psicologico.TestePsicologico', verbose_name='Teste Psicológico'),
        ),
    ]
