# Generated by Django 2.1.1 on 2018-10-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afirmativa',
            name='resposta_esperada',
            field=models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('I', 'Discordo Totalmente')], max_length=3, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_esperada',
            field=models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('I', 'Discordo Totalmente')], max_length=3, verbose_name='Resposta'),
        ),
    ]
