# Generated by Django 2.1.1 on 2018-10-17 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0003_auto_20181016_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afirmativa',
            options={'ordering': ['ordem'], 'verbose_name': 'Afirmativa', 'verbose_name_plural': 'Afirmativas'},
        ),
        migrations.AlterField(
            model_name='resposta',
            name='afirmativa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teste_psicologico.Afirmativa', verbose_name='Afirmativa'),
        ),
    ]
