# Generated by Django 2.1.1 on 2018-10-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0004_auto_20181017_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='testepsicologico',
            name='pontuacao_maxima',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Pontuação Máxima'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testepsicologico',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Resultado (%)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='afirmativa',
            name='resposta_esperada',
            field=models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('DT', 'Discordo Totalmente')], max_length=3, verbose_name='Resposta Esperada'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('DT', 'Discordo Totalmente')], max_length=1, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_esperada',
            field=models.CharField(choices=[('CT', 'Concordo Totalmente'), ('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo'), ('DT', 'Discordo Totalmente')], max_length=3, verbose_name='Resposta Esperada'),
        ),
    ]
