# Generated by Django 2.1.1 on 2018-10-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0005_auto_20181017_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testepsicologico',
            name='pontuacao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pontuação'),
        ),
        migrations.AlterField(
            model_name='testepsicologico',
            name='pontuacao_maxima',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Pontuação Máxima'),
        ),
        migrations.AlterField(
            model_name='testepsicologico',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Resultado (%)'),
        ),
    ]
