# Generated by Django 2.1.1 on 2018-10-18 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0006_auto_20181017_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afirmativa',
            name='resposta_esperada',
            field=models.CharField(choices=[('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo')], max_length=3, verbose_name='Resposta Esperada'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.CharField(choices=[('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo')], max_length=1, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_esperada',
            field=models.CharField(choices=[('C', 'Concordo'), ('I', 'Indiferente'), ('D', 'Discordo')], max_length=3, verbose_name='Resposta Esperada'),
        ),
    ]
