# Generated by Django 2.1.1 on 2019-11-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0031_auto_20191106_1209'),
        ('teste_psicologico', '0007_auto_20181018_2016'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateTestePsicologico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Template de Teste Psicológico',
                'verbose_name_plural': 'Templates de Testes Psicológicos',
            },
        ),
        migrations.AlterModelOptions(
            name='testepsicologico',
            options={'verbose_name': 'Teste Psicológico', 'verbose_name_plural': 'Testes Psicológicos'},
        ),
        migrations.RemoveField(
            model_name='afirmativa',
            name='resposta_esperada',
        ),
        migrations.RemoveField(
            model_name='resposta',
            name='resposta_esperada',
        ),
        migrations.RemoveField(
            model_name='testepsicologico',
            name='pontuacao',
        ),
        migrations.RemoveField(
            model_name='testepsicologico',
            name='pontuacao_maxima',
        ),
        migrations.RemoveField(
            model_name='testepsicologico',
            name='resultado',
        ),
        migrations.AddField(
            model_name='resposta',
            name='midia',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Mídia'),
        ),
        migrations.AddField(
            model_name='testepsicologico',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta',
            field=models.TextField(blank=True, null=True, verbose_name='Resposta'),
        ),
        migrations.AddField(
            model_name='afirmativa',
            name='template_teste_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teste_psicologico.TemplateTestePsicologico', verbose_name='Template de Teste Psicológico'),
        ),
    ]
