# Generated by Django 2.1.1 on 2019-11-06 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0031_auto_20191106_1209'),
        ('teste_psicologico', '0008_auto_20191106_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='afirmativa',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='perfil.Perfil', verbose_name='Perfil'),
        ),
        migrations.AlterField(
            model_name='afirmativa',
            name='template_teste_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teste_psicologico.TemplateTestePsicologico', verbose_name='Template de Teste Psicológico'),
        ),
    ]
