# Generated by Django 2.1.1 on 2019-11-07 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0009_auto_20191106_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='afirmativa',
            name='teste_psicologico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teste_psicologico.TestePsicologico', verbose_name='Teste Psicológico'),
        ),
    ]
