# Generated by Django 2.1.1 on 2019-11-09 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0011_auto_20191107_1308'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='templatetestepsicologico',
            options={'verbose_name': 'Template de Teste Escrito', 'verbose_name_plural': 'Templates de Testes Escritos'},
        ),
        migrations.AlterModelOptions(
            name='testepsicologico',
            options={'verbose_name': 'Teste Escrito', 'verbose_name_plural': 'Testes Escritos'},
        ),
    ]
