# Generated by Django 2.1.1 on 2019-11-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0012_auto_20191109_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='testepsicologico',
            name='marcar_entrevista',
            field=models.BooleanField(default=False, verbose_name='Marcar Entrevista'),
        ),
    ]
