# Generated by Django 2.1.1 on 2019-12-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teste_psicologico', '0013_testepsicologico_marcar_entrevista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testepsicologico',
            name='aprovado_gestor',
            field=models.CharField(choices=[('n/a', 'Não Avaliado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='n/a', max_length=10, verbose_name='Teste Aprovado'),
        ),
    ]
