# Generated by Django 2.1 on 2018-09-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnoFormacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=150, verbose_name='Ano')),
            ],
        ),
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.CharField(max_length=150, verbose_name='Horas')),
                ('pontos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Especializacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('pontos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoAcademica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('pontos', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('pontos', models.IntegerField()),
                ('nivel', models.CharField(choices=[('BAS', 'Básico'), ('INT', 'Intermediário'), ('AVA', 'Avançado')], default='BAS', max_length=3, verbose_name='Nível')),
            ],
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
            ],
        ),
    ]
