# Generated by Django 2.1 on 2018-09-13 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoformacao',
            options={'verbose_name': 'Ano de Formação', 'verbose_name_plural': 'Anos de Formação'},
        ),
        migrations.AlterModelOptions(
            name='cargahoraria',
            options={'verbose_name': 'Carga Horária', 'verbose_name_plural': 'Cargas Horárias'},
        ),
        migrations.AlterModelOptions(
            name='especializacao',
            options={'verbose_name': 'Especialização', 'verbose_name_plural': 'Especializações'},
        ),
        migrations.AlterModelOptions(
            name='formacaoacademica',
            options={'verbose_name': 'Formação Acadêmica', 'verbose_name_plural': 'Formações Acadêmicas'},
        ),
        migrations.AlterModelOptions(
            name='instituicao',
            options={'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
    ]
