# Generated by Django 2.1 on 2018-09-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0003_curso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
    ]
