# Generated by Django 2.1.1 on 2018-10-04 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0005_remove_curso_carga_horaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instituicao',
            options={'ordering': ['nome'], 'verbose_name': 'Instituição', 'verbose_name_plural': 'Instituições'},
        ),
    ]
