# Generated by Django 2.1.1 on 2018-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0006_auto_20181004_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoformacao',
            options={'ordering': ['ano'], 'verbose_name': 'Ano de Formação', 'verbose_name_plural': 'Anos de Formação'},
        ),
        migrations.AlterModelOptions(
            name='cargahoraria',
            options={'ordering': ['horas'], 'verbose_name': 'Carga Horária', 'verbose_name_plural': 'Cargas Horárias'},
        ),
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['titulo'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AlterModelOptions(
            name='especializacao',
            options={'ordering': ['titulo'], 'verbose_name': 'Especialização', 'verbose_name_plural': 'Especializações'},
        ),
        migrations.AlterModelOptions(
            name='formacaoacademica',
            options={'ordering': ['titulo'], 'verbose_name': 'Formação Acadêmica', 'verbose_name_plural': 'Formações Acadêmicas'},
        ),
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['titulo']},
        ),
    ]
