# Generated by Django 2.1.1 on 2019-10-15 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0039_auto_20191015_1148'),
        ('formacao', '0009_auto_20181010_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idioma',
            name='pontos',
        ),
        migrations.AddField(
            model_name='idioma',
            name='certificado',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='idioma',
            name='pessoa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pessoa.Pessoa', verbose_name='Pessoa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='idioma',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Idioma'),
        ),
    ]
