# Generated by Django 2.1.1 on 2019-10-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0010_auto_20191015_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='descricao_midia',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição da Mídia'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='titulo_midia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título da Mídia'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='url_midia',
            field=models.URLField(blank=True, null=True, verbose_name='Link da Mídia'),
        ),
    ]
