# Generated by Django 2.1.1 on 2019-11-01 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0011_auto_20191023_1104'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idioma',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='idioma',
            old_name='titulo',
            new_name='idioma',
        ),
    ]
