# Generated by Django 2.1.1 on 2019-11-01 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0012_auto_20191101_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idioma',
            name='descricao_midia',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='titulo_midia',
        ),
        migrations.RemoveField(
            model_name='idioma',
            name='url_midia',
        ),
    ]
