# Generated by Django 2.1.1 on 2019-11-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacao', '0013_auto_20191101_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='nivel',
            field=models.CharField(choices=[('BAS', 'Básico'), ('BAI', 'Básico a Intermediário'), ('INT', 'Intermediário'), ('AVA', 'Avançado'), ('FLU', 'Fluente/nativo')], default='BAS', max_length=3, verbose_name='Nível'),
        ),
    ]
