# Generated by Django 2.1.1 on 2019-12-09 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.CharField(max_length=250, verbose_name='Competência')),
                ('tipo', models.CharField(choices=[('N', 'Negócios'), ('P', 'Pessoas')], max_length=1, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Competência',
                'verbose_name_plural': 'Competências',
                'ordering': ['competencia'],
            },
        ),
        migrations.CreateModel(
            name='Potencial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencial', models.CharField(max_length=250, verbose_name='Potencial')),
            ],
            options={
                'verbose_name': 'Potencial',
                'verbose_name_plural': 'Potenciais',
                'ordering': ['potencial'],
            },
        ),
    ]
