# Generated by Django 2.1.1 on 2019-12-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0002_competencia_explicativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='potencial',
            name='explicativo',
            field=models.TextField(blank=True, null=True, verbose_name='Explicativo'),
        ),
    ]
