# Generated by Django 2.1.1 on 2019-12-09 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao_desempenho', '0002_grupoavaliacaodesempenho'),
        ('configuracao_avaliacao_desempenho', '0003_potencial_explicativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.TextField(verbose_name='Meta')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso')),
                ('explicativo', models.TextField(blank=True, null=True, verbose_name='Explicativo')),
                ('resultado_esperado', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Resultado Esperado')),
                ('percentual_atingido', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Percentual Atingido (%)')),
                ('forma_medicao', models.CharField(choices=[('QT', 'Quantitativa'), ('QA', 'Qualitativa')], max_length=2, verbose_name='Forma de Medição')),
                ('descricao_resultado', models.TextField(blank=True, null=True, verbose_name='Descrição do Resultado')),
                ('grupo_avaliacao_desempenho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao_desempenho.GrupoAvaliacaoDesempenho', verbose_name='Grupo de Avaliação de Desempenho')),
            ],
            options={
                'verbose_name': 'Meta',
                'verbose_name_plural': 'Metas',
                'ordering': ['meta'],
            },
        ),
    ]
