# Generated by Django 2.1.1 on 2019-12-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0004_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meta',
            name='descricao_resultado',
        ),
        migrations.RemoveField(
            model_name='meta',
            name='percentual_atingido',
        ),
    ]
