# Generated by Django 2.1.1 on 2019-12-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0005_auto_20191209_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='autoavaliacao',
            field=models.BooleanField(default=False, verbose_name='Autoavaliação'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='gestor',
            field=models.BooleanField(default=False, verbose_name='Gestor'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='par',
            field=models.BooleanField(default=False, verbose_name='Par'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='subordinado',
            field=models.BooleanField(default=False, verbose_name='Subordinado'),
        ),
    ]
