# Generated by Django 2.1.1 on 2019-12-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0006_auto_20191229_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='categoria',
            field=models.CharField(choices=[('lider', 'Líder'), ('liderado', 'Liderado')], default='liderado', max_length=15, verbose_name='Categoria'),
        ),
    ]
