# Generated by Django 2.2.4 on 2020-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0007_competencia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='exibir_titulo',
            field=models.BooleanField(default=False, verbose_name='Exibir o Título'),
        ),
        migrations.AddField(
            model_name='competencia',
            name='explicativo_titulo',
            field=models.TextField(blank=True, null=True, verbose_name='Explicativo do Título'),
        ),
    ]
