# Generated by Django 2.2.4 on 2020-02-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao_avaliacao_desempenho', '0008_auto_20200124_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
